### ISSUE TITLE
Host App in Cloud

### ISSUE THREAD

**Issue by davidgfitzgerald** [davidgfitzgerald/time-tracker#8]
# Tasks

- [x] Dockerise app
- [x] Write terraform to deploy
- [x] Build AWS Infra
- [x] Set up EC2 instance
- [x] Push docker image to ECR
- [x] Host app in AWS (ECS?)
- [x] Check monthly costs
- [x] Check app can communicate with DB
- [x] Implement CI/CD to quickly replace prod
- [x] Determine whether to use docker yet
